version: "2"

services:
  app:
    image: golang:1.8
    command: CompileDaemon -command=app
    volumes:
      - .:/go/src/app
    ports:
      - "8080:8080"
      - "3000:3000"
    working_dir: /go/src/app
